
import java.awt.Color;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Dashboard extends javax.swing.JFrame {

     public static String userName;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel_ManageBudget = new javax.swing.JLabel();
        jLabel_AddBudget = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 222, 89));
        jPanel4.setPreferredSize(new java.awt.Dimension(1920, 900));

        jPanel5.setBackground(new java.awt.Color(37, 150, 190));

        jLabel_ManageBudget.setBackground(new java.awt.Color(97, 44, 9));
        jLabel_ManageBudget.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_ManageBudget.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ManageBudget.setText("MANAGE BUDGET");
        jLabel_ManageBudget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ManageBudget.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_ManageBudgetMouseMoved(evt);
            }
        });
        jLabel_ManageBudget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ManageBudgetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_ManageBudgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_ManageBudgetMouseExited(evt);
            }
        });

        jLabel_AddBudget.setBackground(new java.awt.Color(97, 44, 9));
        jLabel_AddBudget.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_AddBudget.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_AddBudget.setText("ADD BUDGET");
        jLabel_AddBudget.setToolTipText("");
        jLabel_AddBudget.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_AddBudget.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel_AddBudgetMouseMoved(evt);
            }
        });
        jLabel_AddBudget.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AddBudgetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_AddBudgetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_AddBudgetMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel_ManageBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(jLabel_AddBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_AddBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_ManageBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 565, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_ManageBudgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ManageBudgetMouseClicked
        ManageBudget mb = new ManageBudget();
        mb.setVisible(true);
        mb.pack();
        mb.setLocationRelativeTo(null);
        mb.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jLabel_ManageBudgetMouseClicked

    private void jLabel_AddBudgetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AddBudgetMouseMoved

    }//GEN-LAST:event_jLabel_AddBudgetMouseMoved

    private void jLabel_AddBudgetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AddBudgetMouseClicked
        AddBudget ab = new AddBudget();
        ab.setVisible(true);
        ab.pack();
        ab.setLocationRelativeTo(null);
        ab.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    }//GEN-LAST:event_jLabel_AddBudgetMouseClicked

    private void jLabel_ManageBudgetMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ManageBudgetMouseMoved
      
    }//GEN-LAST:event_jLabel_ManageBudgetMouseMoved

    private void jLabel_ManageBudgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ManageBudgetMouseEntered
         jLabel_ManageBudget.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_ManageBudgetMouseEntered

    private void jLabel_ManageBudgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ManageBudgetMouseExited
         jLabel_ManageBudget.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_ManageBudgetMouseExited

    private void jLabel_AddBudgetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AddBudgetMouseEntered
       jLabel_AddBudget.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel_AddBudgetMouseEntered

    private void jLabel_AddBudgetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AddBudgetMouseExited
          jLabel_AddBudget.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel_AddBudgetMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_AddBudget;
    private javax.swing.JLabel jLabel_ManageBudget;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
